### PR TITLE
FIX: Point to bin folder not typhon source

### PR DESCRIPTION
**Pull request by teddyrendahl**
Slight error in `typhon_env.sh` script from #130

### CODE REVIEW

**Comment by ZLLentz** [comment]
Does this file belong in bin?

**Comment by teddyrendahl** [comment]
Where would you place it? I guess you don't want to execute it you want to source it. Just put in a `scripts` directory?

**Comment by klauer** [comment]
`etc`, `scripts`...?

**Comment by ZLLentz** [comment]
Sorry! I should have been more specific. I meant `typhon_designer_plugin.py`. It's not a script you run or source in any sense.

**Comment by ZLLentz** [comment]
e.g. maybe you need to move the python file, not change the directory you set in the environment variable

**Comment by teddyrendahl** [comment]
So I can't point to the source because whatever disgusting thing that `QtDesigner` does to run that file craps out with relative imports. I guess that doesn't necessarily require that file living outside that directory though...

**Comment by ZLLentz** [comment]
I still think it's structurally inconsistent to have non-executable python scripts in bin. It will be confusing when I look in bin to find any typhon scripts, and it will be confusing when I go looking for the qt designer plugins and find them in the executables directory. But I won't harp on this any more.

**Pull request merged**
